---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: evergreen-ui
  description: UI for Evergreen
  annotations:
    evergreen/project-id: 65f08ccac9ec449f57b4015d
spec:
  type: website
  owner: group:default/oktagroup_61a3e0b2f29b988eeef4f7b1  # 10gen-evergreen-team okta group
  lifecycle: production
  system: evergreen
  dependsOn:
    - component:default/Sentry
    - component:default/Honeycomb
    - component:default/evergreen-backend
  consumesApis:
    - evergreen-api-graphql

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: spruce
  annotations:
    evergreen/project-id: 65f08ccac9ec449f57b4015d
spec:
  type: website
  owner: group:default/oktagroup_61a3e0b2f29b988eeef4f7b1  # 10gen-evergreen-team okta group
  lifecycle: production
  system: evergreen
  subcomponentOf: evergreen-ui

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: parsley
  description: Evergreen log viewer
  annotations:
    evergreen/project-id: 65f08ccac9ec449f57b4015d
spec:
  type: website
  owner: group:default/oktagroup_61a3e0b2f29b988eeef4f7b1  # 10gen-evergreen-team okta group
  lifecycle: production
  system: evergreen
  subcomponentOf: evergreen-ui

